spring:
  application:
    name: employee-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres  # Use default PostgreSQL superuser for development
    password: 20040622Wzz@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # recreate table every time restart the application
    show-sql: true      # Log SQL queries for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true  # Format SQL queries in logs
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: false

  security:
    user:
      name: wu          # Default Spring Security user for development
      password: 123

server:
  port: 8080

logging:
  level:
    '[edu.uw.cs.zongzewu]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.jdbc.datasource.init]': DEBUG
    '[org.springframework.boot.sql.init]': DEBUG

# CORS config
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000}